version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: cesar-ombi_server_1
      APP_PORT: 3579

  server:
    image: linuxserver/ombi:4.53.4
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      TZ: America/Los_Angeles
      PUID: "1000"
      PGID: "1000"
