version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: cesar-ombi_web_1
      APP_PORT: 5000

  server:
    image: linuxserver/ombi:version-v4.53.4
    container_name: ombi_server_1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    user: "1000:1000"
    init: true
